# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

def common_install_pods
  pod 'SwiftLint', '0.39.2'
  pod 'LicensePlist', '2.15.1'
end

target 'Models' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Models
  pod 'Alamofire', '5.1.0'
  common_install_pods

  target 'ModelsTests' do
    # Pods for testing
  end

end

target 'SwiftArchitecture2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftArchitecture2
  pod 'PKHUD', '5.2.1'
  common_install_pods

  target 'SwiftArchitecture2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftArchitecture2UITests' do
    # Pods for testing
  end

end

target 'Views' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Views
  common_install_pods

  target 'ViewsTests' do
    # Pods for testing
  end

end
