# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Models' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Models
  pod 'Alamofire'

  target 'ModelsTests' do
    # Pods for testing
  end

end

target 'SwiftArchitecture2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftArchitecture2
  pod 'PKHUD', '5.2.1'

  target 'SwiftArchitecture2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftArchitecture2UITests' do
    # Pods for testing
  end

end

target 'Views' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Views

  target 'ViewsTests' do
    # Pods for testing
  end

end
